version: '3.8'

services:
  backend:
    image: host.docker.internal:5001/backend:${APP_VERSION}
    ports:
      - "8082:8080"

  frontend:
    image: host.docker.internal:5001/frontend:${APP_VERSION}
    ports:
      - "81:80"
