version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    environment:
      MYSQL_DATABASE: ITS
      MYSQL_USER: itsapp
      MYSQL_PASSWORD: pass4itsapp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    hostname: db-server
    networks:
      default:
        aliases:
          - db.local
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s 

  backend:
    image: host.docker.internal:5001/backend:${APP_VERSION}
    ports:
      - "8082:8080"

  frontend:
    image: host.docker.internal:5001/frontend:${APP_VERSION}
    ports:
      - "81:80"
